// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: instrument.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Instrument_Type int32

const (
	Instrument_NEW    Instrument_Type = 0
	Instrument_UPDATE Instrument_Type = 1
	Instrument_DELETE Instrument_Type = 2
)

// Enum value maps for Instrument_Type.
var (
	Instrument_Type_name = map[int32]string{
		0: "NEW",
		1: "UPDATE",
		2: "DELETE",
	}
	Instrument_Type_value = map[string]int32{
		"NEW":    0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x Instrument_Type) Enum() *Instrument_Type {
	p := new(Instrument_Type)
	*p = x
	return p
}

func (x Instrument_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instrument_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_instrument_proto_enumTypes[0].Descriptor()
}

func (Instrument_Type) Type() protoreflect.EnumType {
	return &file_instrument_proto_enumTypes[0]
}

func (x Instrument_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instrument_Type.Descriptor instead.
func (Instrument_Type) EnumDescriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0, 0}
}

type Instrument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User              string                `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	MessageType       Instrument_Type       `protobuf:"varint,2,opt,name=messageType,proto3,enum=api.Instrument_Type" json:"messageType,omitempty"`
	InstrumentPayload []*Instrument_Payload `protobuf:"bytes,3,rep,name=instrumentPayload,proto3" json:"instrumentPayload,omitempty"`
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instrument_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0}
}

func (x *Instrument) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Instrument) GetMessageType() Instrument_Type {
	if x != nil {
		return x.MessageType
	}
	return Instrument_NEW
}

func (x *Instrument) GetInstrumentPayload() []*Instrument_Payload {
	if x != nil {
		return x.InstrumentPayload
	}
	return nil
}

type Instrument_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Isin string `protobuf:"bytes,2,opt,name=isin,proto3" json:"isin,omitempty"`
}

func (x *Instrument_Payload) Reset() {
	*x = Instrument_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_instrument_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instrument_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument_Payload) ProtoMessage() {}

func (x *Instrument_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument_Payload.ProtoReflect.Descriptor instead.
func (*Instrument_Payload) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Instrument_Payload) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Instrument_Payload) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

var File_instrument_proto protoreflect.FileDescriptor

var file_instrument_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xf7, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x45, 0x0a, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x2d, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x69, 0x6e, 0x22, 0x27, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10,
	0x02, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x64, 0x6a, 0x6f, 0x72, 0x64, 0x6a, 0x65, 0x76, 0x69, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_instrument_proto_rawDescOnce sync.Once
	file_instrument_proto_rawDescData = file_instrument_proto_rawDesc
)

func file_instrument_proto_rawDescGZIP() []byte {
	file_instrument_proto_rawDescOnce.Do(func() {
		file_instrument_proto_rawDescData = protoimpl.X.CompressGZIP(file_instrument_proto_rawDescData)
	})
	return file_instrument_proto_rawDescData
}

var file_instrument_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instrument_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_instrument_proto_goTypes = []interface{}{
	(Instrument_Type)(0),       // 0: api.Instrument.Type
	(*Instrument)(nil),         // 1: api.Instrument
	(*Instrument_Payload)(nil), // 2: api.Instrument.Payload
}
var file_instrument_proto_depIdxs = []int32{
	0, // 0: api.Instrument.messageType:type_name -> api.Instrument.Type
	2, // 1: api.Instrument.instrumentPayload:type_name -> api.Instrument.Payload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_instrument_proto_init() }
func file_instrument_proto_init() {
	if File_instrument_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_instrument_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instrument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_instrument_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instrument_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_instrument_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instrument_proto_goTypes,
		DependencyIndexes: file_instrument_proto_depIdxs,
		EnumInfos:         file_instrument_proto_enumTypes,
		MessageInfos:      file_instrument_proto_msgTypes,
	}.Build()
	File_instrument_proto = out.File
	file_instrument_proto_rawDesc = nil
	file_instrument_proto_goTypes = nil
	file_instrument_proto_depIdxs = nil
}
